from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch

def generate_pdf_report(save_path, file_path, scan_results, status_text):
    try:
        c = canvas.Canvas(save_path, pagesize=A4)
        width, height = A4  # (595.27, 841.89)

        # Set up coordinates
        x = 1 * inch
        y = height - (1 * inch)
        line_height = 0.25 * inch

        # --- Title ---
        c.setFont("Helvetica-Bold", 16)
        c.drawString(x, y, "File Scan Report")
        y -= (line_height * 2)

        # --- File Path ---
        c.setFont("Helvetica-Bold", 12)
        c.drawString(x, y, "Scanned File:")
        c.setFont("Helvetica", 11)
        # Handle long file paths
        if len(file_path) > 80:
             c.drawString(x, y - line_height, file_path[:80] + "...")
        else:
             c.drawString(x, y - line_height, file_path)
        y -= (line_height * 3)

        # --- Status ---
        c.setFont("Helvetica-Bold", 14)
        c.drawString(x, y, status_text)
        
        # Set color for status
        if "LEGITIMATE" in status_text:
            c.setFillColorRGB(0, 0.6, 0) # Green
        elif "SPOOF" in status_text:
            c.setFillColorRGB(0.8, 0, 0) # Red
        elif "UNKNOWN" in status_text:
            c.setFillColorRGB(0.9, 0.5, 0) # Yellow
            
        c.drawString(x, y, status_text)
        c.setFillColorRGB(0, 0, 0) # Reset to black
        y -= (line_height * 2)

        # --- Metadata ---
        c.setFont("Helvetica-Bold", 12)
        c.drawString(x, y, "File Metadata:")
        y -= (line_height * 1.5)
        
        c.setFont("Helvetica", 11)
        
        def draw_key_value(key, value):
            nonlocal y
            # Truncate long values
            if len(value) > 100:
                value = value[:100] + "..."
            
            c.drawString(x, y, f"{key}:")
            c.drawString(x + (1.8 * inch), y, value)
            y -= line_height

        draw_key_value("Original Extension", scan_results.get('extension', 'N/A'))
        draw_key_value("Detected MIME", scan_results.get('detected_mime', 'N/A'))
        draw_key_value("Description", scan_results.get('description', 'N/A'))
        
        y -= (line_height * 0.5) # Spacer
        
        draw_key_value("Size", scan_results.get('size', 'N/A'))
        draw_key_value("Created", scan_results.get('creation_time', 'N/A'))
        draw_key_value("Modified", scan_results.get('modified_time', 'N/A'))
        
        y -= (line_height * 0.5) # Spacer
        
        # Handle long hash
        c.drawString(x, y, "SHA256 Hash:")
        hash_val = scan_results.get('hash_sha256', 'N/A')
        # Split hash into two lines if needed, but it should fit
        c.drawString(x, y - line_height, hash_val)
        y -= (line_height * 2)
        

        # --- Footer ---
        c.setFont("Helvetica-Oblique", 9)
        c.drawCentredString(width / 2.0, 0.75 * inch, "Report generated by File Metadata Scanner")

        # Save the PDF
        c.save()
        print(f"Report saved to {save_path}")
        return True
    
    except Exception as e:
        print(f"Error generating PDF report: {e}")
        return False

if __name__ == '__main__':
    # A simple test to run this file directly
    print("Testing PDF report generation...")
    test_results = {
        'extension': '.pdf',
        'detected_mime': 'text/plain',
        'description': 'ASCII text',
        'size': '1.23 MB',
        'hash_sha256': 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2',
        'creation_time': '2023-01-01 10:00:00',
        'modified_time': '2023-01-01 11:00:00'
    }
    test_file_path = "/path/to/my/fake.pdf"
    test_status = "Status: POTENTIAL SPOOF!"
    
    success = generate_pdf_report("test_report.pdf", test_file_path, test_results, test_status)
    if success:
        print("Test PDF 'test_report.pdf' created successfully.")
    else:
        print("Test PDF generation failed.")
